//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCodeGenerate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function
    {
        public int Id { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string IconUrl { get; set; }
        public string CssStyle { get; set; }
        public string HttpMethod { get; set; }
        public string IsAvailable { get; set; }
        public string ParentId { get; set; }
        public int PermissionId { get; set; }
        public int FunctionType { get; set; }
    
        public virtual Permission Permission { get; set; }
    }
}
